groupmy/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources :groups do
		member do
			post :join
			post :quit
		end
		resources :posts
	end
	namespace :account do
		resources :group
		resources :posts
	end
	
	root :to => "groups#index"

 	

end

groupmy/app/models/group.rb
class Group < ActiveRecord::Base
	validates :title, :presence => true
	has_many :posts
	has_many :group_users
	has_many :members, :through => :group_users ,  :source => :group
	belongs_to :owner, :class_name => "User", :foreign_key => :user_id


	def editable_by?(user)
		user && user == owner
	end

end

groupmy/app/models/group_user.rb
class GroupUser < ActiveRecord::Base
	  belongs_to :user
	  belongs_to :group
end

groupmy/app/models/participated_groups.rb
class ParticipatedGroups < ActiveRecord::Base
end

groupmy/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :group, :counter_cache => true
	validates :content, :presence => true
	belongs_to :author, :class_name => "User", :foreign_key => :user_id


	def editable_by?(user)
		user && user == author
	end

end

groupmy/app/models/user.rb
class User < ActiveRecord::Base
  has_many :groups
  has_many :posts
  has_many :group_users
  has_many :participated_groups, :through => :group_users, :source => :group


	# Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def join!(group)
  	participated_groups << group
  end

  def quit!(group)
  	participated_groups.delete(group)
  end

  def is_member_of?(group)
  	participated_groups.include?(group)
  end


end

groupmy/app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController
	before_action :login_required

	def index
		@group = current_user.participated_groups
	end

	
end

groupmy/app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController

	def index
		@posts = current_user.posts.order("updated_at DESC")
	end

end

groupmy/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 	protected
	def configure_permitted_parameters
					devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
	end

	def login_required
		if current_user.blank?
			respond_to do |format|
			format.html {
				authenticate_user!
			}
			format.js{
				render :partial => "common/not_logined"
			}
			format.all {
				head(:unauthorized)
			}
			end
		end
	end

  protect_from_forgery with: :exception
end

groupmy/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_action :find_group, :only => [:show, :edit, :update, :destroy]
	before_action :login_required, :only => [:new, :create, :edit,:update,:destroy]


	def index
		@groups = Group.all
	end

	def show
		@posts = @group.posts
	end

	def new
		@group = Group.new
	end

	def edit
	end

	def update
		if @group.update(group_params)
			redirect_to group_path(@group)
		else
			render :edit
		end
	end

	def create
		@group = current_user.groups.build(group_params)
		if @group.save
			current_user.join!(@group)
			redirect_to groups_path
		else
			render :new
		end
	end

	
  	def destroy
 		@group.destroy
  		redirect_to groups_path
	end

	def join
		@group = Group.find(params[:id])
		
		if !current_user.is_member_of?(@group)
			current_user.join!(@group)
		else
			flash[:warning] = "You are already join this group!"
		end
		redirect_to groups_path(@group)
	end	

	def quit
		@group = Group.find(params[:id])
		if current_user.is_member_of?(@group)
			current_user.quit!(@group)
		else
			flash[:warning] = "You are already join this group!"
		end
		redirect_to groups_path(@group)
	end
	private

		def group_params
			params.require(:group).permit(:title, :description)
		end

		def find_group
			@group = Group.find(params[:id])
		end
end

groupmy/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
	def welcome

	end

end

groupmy/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :login_required, :only => [:new, :create, :edit,:update,:destroy]
	before_action :member_required, :only => [:new, :create ]


	def new
		@group = Group.find(params[:group_id])
		@post = @group.posts.build
	end

	def create
		@group = Group.find(params[:group_id])
		@post =@group.posts.new(post_params)

		if @post.save
			redirect_to group_path(@group)
		else
			render :new
		end
	end

	def edit
		@post = current_user.posts.find(params[:id])
	end


	def update
		@post = current_user.posts.find(params[:id])


		if @post.update(post_params)
			redirect_to group_path(@group)
		else
			render :edit
		end
	end

	def destroy
		@post = current_user.posts.find(params[:id])
		@posts.destroy
		redirect_to group_path(@group)
	end

	def member_required
		@group = Group.find(params[:group_id])
		if !current_user.is_member_of?(@group)
			flash[:warning] = " You are not member of this group!"
			redirect_to group_path(@group)
		end
	end

	private
	
	def post_params
		params.require(:post).permit(:content)
	end
end

groupmy/app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

groupmy/app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

groupmy/app/helpers/application_helper.rb
module ApplicationHelper
end

groupmy/app/helpers/groups_helper.rb
module GroupsHelper
end

groupmy/app/helpers/pages_helper.rb
module PagesHelper
end

groupmy/app/helpers/posts_helper.rb
module PostsHelper
end

groupmy/app/views/groups/edit.html.erb
<div class="span12">
	<%= form_for @group do |f| %>
		<%= f.text_field :title, :input_html => { :class => "input-xxlarge"} %>
		<%= f.text_field :description, :input_html => { :class => "input-xxlarge"} %>
	<div class="form-actions">
					<%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn\
					-primary" %>
	</div>
	<% end %>
</div>

groupmy/app/views/groups/index.html.erb
<div class="span12">
	<%= link_to( "Login", new_user_session_path ) %>
 	<%= link_to( "Sign Up" ,new_user_registration_path) %>

	<div class="group">
	<%= link_to("New group", new_group_path , :class => "btn btn-mini btn-primary\
pull-right")%>
	</div>
	<table class="table">
		<thead> <tr>
			<td> # </td>
				<td> Title </td>
				<td> Descroption </td>
				<td> Owner </td>
				</tr>
				</thead>
		<tbody>
	<% @groups.each do |group| %>
	<tr>
		<td> # </td>
		<td> <%= link_to(group.title, group_path(group)) %> </td>
		<td> <%= group.description %> </td>
	<td>
	<% if current_user && group.editable_by?(current_user) %>
	<%= link_to("Edit", edit_group_path(group), :class => "btn btn-mini")%>
	<%= link_to("Delete", group_path(group), :class => "btn btn-mini", :method => :delete, :confirm => "Are you sure?" ) %>
		<% end %>
	</td>
	</tr>
	<% end %>
	</tbody>
	</table>
</div>

groupmy/app/views/groups/new.html.erb
<div class="span12">
	<%= form_for @group do |f| %>
		<%= f.text_field :title, :input_html => { :class => "input-xxlarge"} %>
		<%= f.text_field :description, :input_html => { :class => "input-xxlarge"} %>
	<div class="form-actions">
					<%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn\
					-primary" %>
	</div>
	<% end %>
</div>

groupmy/app/views/groups/show.html.erb
<div class="span12">
	<div class="group pull-right">
		<% if current_user && @group.editable_by?(current_user) %>
			<%= link_to("Edit", edit_group_path(@group) , :class => "btn btn-mini ")%>
		<% end %>
		<%= link_to("New Post", new_group_post_path(@group) , :class => "btn btn-mini btn-primary"  )%>
	&nbsp;
	</div>
	<h2> <%= @group.title %> </h2>
	<p> <%= @group.description %> </p>
	<table class="table">
		<tbody>
		<% @posts.each do |post| %>
			<tr>
				<td>
<p>
<%= post.content %>
	</p>
</td>
		<% if current_user && post.editable_by?(current_user) %>
	<td> <%= link_to("Edit", edit_group_post_path(post.group, post), :class => "btn btn-mini")%>
	<%= link_to("Delete", group_post_path(post.group, post), :class => "btn b\
	tn-mini", :method => :delete, :confirm => "Are you sure?" ) %> </td>
	</tr>
	<% end %>
	<% end %>
	</tbody>
	</table>
</div>

<% if current_user %>
<div class="group pull-right">
<% if current_user.is_member_of?(@group) %>
<%= link_to("Quit Group", quit_group_path(@group), :method => :post, :class => "btn btn-mini") %>
<% else %>
<%= link_to("Join Group", join_group_path(@group), :method => :post, :class => "btn btn-mini") %>
<% end %>
</div>
<% end %>

groupmy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Groupmy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

groupmy/app/views/pages/welcome.html.erb
hello world!

groupmy/app/views/posts/edit.html.erb
<div class="span12">
	<%= simple_form_for [@group,@post] do |f| %>
	<%= f.input :content, :input_html => { :class => "input-xxlarge"} %>
	<div class="form-actions">
<%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn\
-primary" %>
</div>
<% end %>
</div>

groupmy/app/views/posts/new.html.erb
<div class="span12">
	<%= form_for [@group,@post] do |f| %>
		<%= f.text_field :content, :input_html => { :class => "input-xxlarge"} %>
	<div class="form-actions">
					<%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn\
					-primary" %>
	</div>
	<% end %>
</div>